name: ci-build

on:
  push:


jobs:
  # Main build, creates firmware update image
  build-soc:
    runs-on: ubuntu-latest
    steps:
    # Checkout Repository
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: false # Note: not Recursive (we don't need GB's of tinyusb deps)

    - name: Checkout Submodule
      run: |
        git submodule update --init
        git submodule update --init --recursive -- gateware/deps/pythondata-software-picolibc

    - name: YosysHQ setup
      uses: YosysHQ/setup-oss-cad-suite@v1
      
    - name: RISC-V GNU setup
      uses: gregdavill/setup-riscv-gnu-toolchain@v1.0
    
    - name: configure python
      run: |
        python3 -m pip install setuptools
        python3 -m pip install pycrc
        python3 -m pip install wheel
        python3 -m pip install construct
        python3 -m pip install Sphinx sphinxcontrib-wavedrom meson ninja setuptools_scm Jinja2
    
    - name: Litex build
      working-directory: ./gateware
      run: |
        python3 butterstick-bitstream.py

    - name: Upload dfu update file
      uses: actions/upload-artifact@v2
      with:
        name: gateware binary
        path: ${{ github.workspace }}/gateware/build/butterstick_r1d0/gateware/butterstick_r1d0.dfu
